config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers:
         { omniauth_callbacks: 'omniauth_callbacks',
           registrations: 'my_devise/registrations',
           confirmations: 'confirmations' }

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  root to: 'post#index'

  resources :profiles, except: [:index]

  resources :post, except: [:index] do
    resources :comments, except: [:index]
    resources :likes
  end
  resources :comments do
    resources :comments
  end

  post 'relationships', to: 'relationships#create'
  post 'relationship',  to: 'relationships#destroy'

  post 'requests', to: 'requests#create'
  post 'request', to: 'requests#destroy'

  get '/search' => 'search#create', :as => 'search_user'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base #:nodoc:
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

# validates and associates Comments
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord #:nodoc:
  has_attached_file :image,
                    styles: { thumb: '100x100#', small: '250x250#',
                              medium: '600x600#' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
  belongs_to :imageable, polymorphic: true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord #:nodoc:
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord # :nodoc:
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :images, as: :imageable
  has_many :likes, dependent: :destroy
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord #:nodoc:
  belongs_to :user
  has_many :image, as: :imageable
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord #:nodoc:
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  # belongs_to :requesters, class_name: 'User'
  # belongs_to :requested, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord #:nodoc:
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthables
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[google_oauth2 facebook]

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def followers
    follower_relationships.map { |i| User.find(i.follower_id) }
  end

  def followings
    following_relationships.map { |i| User.find(i.following_id) }
  end

  def follower_relationships
    Relationship.where(following_id: id)
  end

  def following_relationships
    Relationship.where(follower_id: id)
  end

  def followed?(user_id)
    followings.find { |user| user.id == user_id }
  end

  def request_sent?(user_id)
    requested.find { |user| user.id == user_id }
  end

  def requesters
    request_received.map { |i| User.find(i.requesting_id) }
  end

  def requested
    request_sent.map { |i| User.find(i.requested_id) }
  end

  def request_sent
    Request.where(requesting_id: id)
  end

  def request_received
    Request.where(requested_id: id)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    # Uncomment the section below if you want users to be created
    # if they don't exist
    user ||= User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )
    user
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController #:nodoc:
  before_action :find_post

  def create
    if !already_liked?
      flash[:notice] = "You can't a like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    render :create
  end

  def destroy
    like = Like.find(params[:id])
    if !like.destroy
      flash[:alert] = 'Sorry! Cannot Unlike the Post.'
    else
      render :create
    end
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).empty?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

class PostController < ApplicationController #:nodoc:
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
    @users = User.all
  end

  def new
    @post = Post.new
  end

  def create
    @post =
      Post.new(title: post_params[:title],
               description: post_params[:description])
    @post.user = current_user
    save_post(@post)
  end

  def show; end

  def edit
    render 'edit'
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Successfully updated!'
      render post_path(@post)
    else
      flash[:alert] = 'Failed to Update!'
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Successfully deleted!'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, image: [])
  end

  def save_post(post)
    if post.save
      save_image post
      flash[:sucess] = 'Successfully created`!'
      redirect_to root_path
    else
      flash[:notice] = 'Something Went wrong!'
      render 'new'
    end
  end

  def save_image(post)
    post_params[:image].each do |img|
      post.images.create(image: img)
    end
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController #:nodoc:
  before_action :authenticate_user!
  before_action :set_profile, only: %i[edit update destroy]
  before_action :profile_params, only: %i[create update]
  before_action :image_params, only: %i[create update]

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save &&
       @profile.image.build(image_params).save
      flash[:notice] = 'Successfully created!'
    else
      flash[:alert] = 'Something Went Wrong!'
    end
    redirect_to profile_path(@profile)
  end

  def show
    @profile = User.find(params[:id]).profile
  end

  def edit
    if @profile.id == current_user.profile.id
      render 'edit'
    else
      flash[:alert] = 'You are not authorized to edit the profile.......'
      redirect_to root_path
    end
  end

  def update
    if @profile.update(profile_params) &&
       @profile.image.build(image_params).save
      flash[:notice] = 'Changes Successfully Updated!'
    else
      flash[:alert] = 'Something Went Wrong!'
    end
    redirect_to profile_path(@profile)
  end

  def destroy
    @profile&.destroy
    flash[:notice] = 'Successfully deleted!'
    redirect_to root_path
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:name, :username,
                                    :website, :bio, :phone_number)
  end

  def image_params
    params.require(:profile).permit(:image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # :nodoc:
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper #:nodoc:
end

app/helpers/confirmations_helper.rb
# frozen_string_literal: true

module ConfirmationsHelper #:nodoc:
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper #:nodoc:
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper #:nodoc:
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper #:nodoc:
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper #:nodoc:
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper #:nodoc:
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper #:nodoc:
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper #:nodoc:
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper #:nodoc:
end

app/views/profiles/create.html.erb
<h1>Profile#create</h1>
<p>Find me in app/views/profile/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profile#destroy</h1>
<p>Find me in app/views/profile/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<div class="row pt-4">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4">
  <%= form_for @profile, url: {action: "update"}  do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_field :bio, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :phone_no%>
      <%= f.text_field :phone_number, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control'%>
    </div>

    <%= f.submit 'Submit', class: 'btn btn-outline-secondary' %>
  <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/profiles/index.html.erb
<h1>Profile#index</h1>
<p>Find me in app/views/profile/index.html.erb</p>

app/views/profiles/new.html.erb
<%= form_with model: @profile, url: profiles_path do |p|%>
    <div class="form-group">
      <%= p.label :name, class:'text-secondary'  %><br/>
      <%= p.text_field :name, placeholder: "Name", class:'form-control' %>
    </div>
    <div class="form-group">
      <%= p.label :username, class:'text-secondary'  %><br/>
      <%= p.text_field :username, placeholder: "Username", class:'form-control' %>
    </div>
    <div class="form-group">
      <%= p.label :website, class:'text-secondary'  %> <br/>
      <%= p.text_field :website, placeholder: "Website", class:'form-control' %>
    </div>
    <div class="form-group">  
      <%= p.label :phone_no, class:'text-secondary'  %> <br/>
      <%= p.text_field :phone_number, placeholder: "Phone Number", class:'form-control'%>
    </div>
    <div class="form-group">
      <%= p.label :image %>
      <%= p.file_field :image, class: 'form-control'%>
    </div>
    <div class="actions signin-button">
      <%= p.submit "Submit", class: 'btn btn-outline-secondary' %>
    </div>
<%end%>

app/views/profiles/show.html.erb
<div class="row pt-4">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <%= render partial: 'layouts/profiledetails', locals: {profile: @profile}%>
  </div>
  </div>
  <div class="col-md-3">
  </div>
</div>