config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers:
         { omniauth_callbacks: 'omniauth_callbacks',
           registrations: 'my_devise/registrations',
           confirmations: 'confirmations' }

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  root to: 'post#index'

  resources :profiles, except: [:index]

  resources :post, except: [:index] do
    resources :comments, except: [:index]
    resources :likes
  end
  resources :comments do
    resources :comments
  end

  post 'relationships', to: 'relationships#create'
  post 'relationship',  to: 'relationships#destroy'

  post 'requests', to: 'requests#create'
  post 'request', to: 'requests#destroy'

  get '/search' => 'search#create', :as => 'search_user'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base #:nodoc:
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

# validates and associates Comments
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord #:nodoc:
  has_attached_file :image,
                    styles: { thumb: '100x100#', small: '250x250#',
                              medium: '600x600#' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
  belongs_to :imageable, polymorphic: true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord #:nodoc:
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord # :nodoc:
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :images, as: :imageable
  has_many :likes, dependent: :destroy
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord #:nodoc:
  belongs_to :user
  has_many :image, as: :imageable
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord #:nodoc:
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  # belongs_to :requesters, class_name: 'User'
  # belongs_to :requested, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord #:nodoc:
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthables
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[google_oauth2 facebook]

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def followers
    follower_relationships.map { |i| User.find(i.follower_id) }
  end

  def followings
    following_relationships.map { |i| User.find(i.following_id) }
  end

  def follower_relationships
    Relationship.where(following_id: id)
  end

  def following_relationships
    Relationship.where(follower_id: id)
  end

  def followed?(user_id)
    followings.find { |user| user.id == user_id }
  end

  def request_sent?(user_id)
    requested.find { |user| user.id == user_id }
  end

  def requesters
    request_received.map { |i| User.find(i.requesting_id) }
  end

  def requested
    request_sent.map { |i| User.find(i.requested_id) }
  end

  def request_sent
    Request.where(requesting_id: id)
  end

  def request_received
    Request.where(requested_id: id)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    # Uncomment the section below if you want users to be created
    # if they don't exist
    user ||= User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )
    user
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController #:nodoc:
  def index
    @image = Image.all
  end

  def new
    @image = Image.new
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController #:nodoc:
  before_action :find_post

  def create
    if !already_liked?
      flash[:notice] = "You can't a like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    render :create
  end

  def destroy
    like = Like.find(params[:id])
    if !like.destroy
      flash[:alert] = 'Sorry! Cannot Unlike the Post.'
    else
      render :create
    end
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).empty?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

class PostController < ApplicationController #:nodoc:
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
    @users = User.all
  end

  def new
    @post = Post.new
  end

  def create
    @post =
      Post.new(title: post_params[:title],
               description: post_params[:description])
    @post.user = current_user
    save_post(@post)
  end

  def show; end

  def edit
    render 'edit'
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Successfully updated!'
      render post_path(@post)
    else
      flash[:alert] = 'Failed to Update!'
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Successfully deleted!'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, image: [])
  end

  def save_post(post)
    if post.save
      save_image post
      flash[:sucess] = 'Successfully created`!'
      redirect_to root_path
    else
      flash[:notice] = 'Something Went wrong!'
      render 'new'
    end
  end

  def save_image(post)
    post_params[:image].each do |img|
      post.images.create(image: img)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # :nodoc:
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper #:nodoc:
end

app/helpers/confirmations_helper.rb
# frozen_string_literal: true

module ConfirmationsHelper #:nodoc:
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper #:nodoc:
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper #:nodoc:
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper #:nodoc:
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper #:nodoc:
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper #:nodoc:
end

app/helpers/relationships_helper.rb
# frozen_string_literal: true

module RelationshipsHelper #:nodoc:
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper #:nodoc:
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper #:nodoc:
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper #:nodoc:
end

app/views/post/_post.html.erb
<div class="media">
  <div class="media-left">
    <% @posts.each do |post|%>
      <%= link_to image_tag(post.image.url, class: 'media-object'), post.image.url, target: '_blank' %>
      <%= link_to 'Destroy',  { action: :destroy, id: post.id }, method: :delete, data: { confirm: 'Are you sure?' } %>

  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= post.title %></h4>
  </div>
    <%end%>
</div>

app/views/post/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/post/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

<%= form_for :profile  do |p|%>
  <div class="pass-input user-input">
    <%= p.label :name %><br/>
    <%= p.text_field :name, placeholder: "Name" %>
  </div>
  <div class="pass-input user-input">
    <%= p.label :username %><br/>
    <%= p.text_field :username, placeholder: "Username" %>
  </div>
  <div class="pass-input user-input">
    <%= p.label :website %> <br/>
    <%= p.text_field :website, placeholder: "Website" %>
  </div>
  <div class="pass-input user-input">  
    <%= p.label :phone_no %> <br/>
    <%= p.text_field :phone_number, placeholder: "Phone Number"%>
  </div>
  <%= p.submit 'Submit' %>
<%end%>

app/views/post/index.html.erb
<%if !current_user.profile.nil? %>
  <div class="row pt-4">
    <div class="col-sm-2">  
    </div>
    <div class="col-sm-9">
      <div class="row">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-7">
          <%@posts.each do |post|%>
            <%= render partial: 'layouts/postcard', locals: {post: post}%> 
            <div class="fence"></div>
          <%end%>   
        </div>
        <div class="col-sm-3">
          <%= render partial: 'layouts/usersection', locals: {post: @posts, users: @users} %>
        </div>
      </div>
    </div>
    <div class="col-sm-1">
    </div>
  </div>
<%else%>
   <div class="row pt-4">
    <div class="col-sm-2">  
    </div>
    <div class="col-sm-9">
        <strong> We didn't find your Profile. You need to <%= link_to ' Create One ', new_profile_path(current_user)%> to continue.</strong>
    </div>
    <div class="col-sm-1">
    </div>
  </div>
<%end%>

app/views/post/new.html.erb
<%= render 'shared/form' %>

app/views/post/show.html.erb
<div class="row mt-4">
  <div class="col-sm-2">
  </div>
  <div class=col-sm-8>  
    <div class="row"> 
      <div class="col-sm-7"> 
        <%= render partial: 'layouts/carousel', locals: {post: @post}, class:"card-img-top"%>
      </div>
      <div class="col-sm-5">
        <div class="card  bg-white" style="width: 18rem;">
         <div class="card-body">
            <h5 class="card-title"><%=@post.title%></h5>
            <p class="card-text"><%=@post.description%></p>
          </div>
          <div class="card-body row">
            <div class="col-sm-6">
              <strong><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></strong>
            </div>
            <div class="col-sm-6">
              <div id="likeunlike">
                <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %> 
                  <%= button_to  post_like_path(@post, pre_like), class: "btn btn-small", method: :delete, remote: true do %> 
                    <i class="fa fa-heart fa-2x unlike"> </i> 
                  <%end%>
                <%else %> 
                  <%= button_to post_likes_path(@post), method: :post, class: "btn btn-small", remote: true do %>
                    <i class="fa fa-heart-o fa-2x"> </i>
                  <%end%>
                <%end%>
              </div>    
            </div>
          </div>
          <div class="list-group list-group-flush">
            <div class="reply">
              <%= form_with(model: [@post, @post.comments.build] ,placeholder: "Add Comments...", local: true) do |form| %>
                <%= form.text_field :body, class: 'comment-box m-1' %>
                <%= form.submit "Comment", class: 'btn btn-outline-secondary'%>
              <% end %>
            </div>
            <div class="list-group-item">
              <% post_comments = @post.comments.find_all { |comment| comment.id != nil} %>
              <%= render partial: 'comments/comments', collection: post_comments %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-2">
  </div>
</div>

app/views/post/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>