config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers:
         { omniauth_callbacks: 'omniauth_callbacks',
           registrations: 'my_devise/registrations',
           confirmations: 'confirmations' }

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  root to: 'post#index'

  resources :profiles, except: [:index]

  resources :post, except: [:index] do
    resources :comments, except: [:index]
    resources :likes
  end
  resources :comments do
    resources :comments
  end

  post 'relationships', to: 'relationships#create'
  post 'relationship',  to: 'relationships#destroy'

  post 'requests', to: 'requests#create'
  post 'request', to: 'requests#destroy'

  get '/search' => 'search#create', :as => 'search_user'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base #:nodoc:
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

# validates and associates Comments
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord #:nodoc:
  has_attached_file :image,
                    styles: { thumb: '100x100#', small: '250x250#',
                              medium: '600x600#' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
  belongs_to :imageable, polymorphic: true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord #:nodoc:
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord # :nodoc:
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :images, as: :imageable
  has_many :likes, dependent: :destroy
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord #:nodoc:
  belongs_to :user
  has_many :image, as: :imageable
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord #:nodoc:
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  # belongs_to :requesters, class_name: 'User'
  # belongs_to :requested, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord #:nodoc:
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthables
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[google_oauth2 facebook]

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def followers
    follower_relationships.map { |i| User.find(i.follower_id) }
  end

  def followings
    following_relationships.map { |i| User.find(i.following_id) }
  end

  def follower_relationships
    Relationship.where(following_id: id)
  end

  def following_relationships
    Relationship.where(follower_id: id)
  end

  def followed?(user_id)
    followings.find { |user| user.id == user_id }
  end

  def request_sent?(user_id)
    requested.find { |user| user.id == user_id }
  end

  def requesters
    request_received.map { |i| User.find(i.requesting_id) }
  end

  def requested
    request_sent.map { |i| User.find(i.requested_id) }
  end

  def request_sent
    Request.where(requesting_id: id)
  end

  def request_received
    Request.where(requested_id: id)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    # Uncomment the section below if you want users to be created
    # if they don't exist
    user ||= User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )
    user
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

class PostController < ApplicationController #:nodoc:
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
    @users = User.all
  end

  def new
    @post = Post.new
  end

  def create
    @post =
      Post.new(title: post_params[:title],
               description: post_params[:description])
    @post.user = current_user
    save_post(@post)
  end

  def show; end

  def edit
    render 'edit'
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Successfully updated!'
      render post_path(@post)
    else
      flash[:alert] = 'Failed to Update!'
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Successfully deleted!'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, image: [])
  end

  def save_post(post)
    if post.save
      save_image post
      flash[:sucess] = 'Successfully created`!'
      redirect_to root_path
    else
      flash[:notice] = 'Something Went wrong!'
      render 'new'
    end
  end

  def save_image(post)
    post_params[:image].each do |img|
      post.images.create(image: img)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # :nodoc:
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper #:nodoc:
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper #:nodoc:
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper #:nodoc:
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper #:nodoc:
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper #:nodoc:
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper #:nodoc:
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper #:nodoc:
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper #:nodoc:
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper #:nodoc:
end

app/views/layouts/_commentbox.html.erb
<div class="row">
  <div class="col-sm-9">
  <%= form_with(model: [post, post.comments.build] ,placeholder: "Add Comments", local: true) do |form| %>
    <%= form.text_field :body, class:"com-box", :id => "comment-box#{post.id}", placeholder: " Add Comments" %><br>
  </div>
  <div class="col-sm-3 ">
    <%= form.submit 'Comment', class: 'btn btn-small comment' %> <br>
  <% end %>
  </div>
</div>

app/views/layouts/_followbutton.html.erb
<div id="followbutton<%=user.id%>">
  <% if current_user.request_sent? user.id %>
    <%= button_to "Cancel Request", request_path(user_id: user.id, status: :canceled), class: "btn btn-outline-warning", method: :post, remote: true %>
  <% elsif current_user.followed?(user.id) %>
    <%= button_to "Unfollow", relationship_path(user_id: user.id), class: "btn btn-outline-danger", :method => :post, remote: true %>
  <% else %>
    <%= button_to "Send Request", requests_path(user_id: user.id), class: "btn btn-outline-secondary", method: :post, remote: true %>
  <% end %>
</div>

app/views/layouts/_footerdetails.html.erb
<div class="mb-3">
  <div class="card-body text-secondary">
    <nav class="navbar d-flex card-text text-muted list-style-type:circle">
      <small>    
        <span>ABOUT US</span>  
        <span>SUPPORT</span> 
        <span>PRESS</span>
        <span>API</span>
        <span>JOBS</span>
        <span>PRIVACY</span>
        <span>TERMS</span>
        <span>DIRECTORY</span>
        <span>PROFILES</span>
        <span>HASHTAGS</span>
        <span>LANGUAGE</span>
        <p> © 2020 IMAGENATE  </p>
      </small>
    </nav>
  </div>
</div>

<!--footer class="container footer">
      <nav class="navbar d-flex">

          ABOUT US
          SUPPORT 
          PRESS
          API
          JOBS
          PRIVACY
          TERMS
          DIRECTORY
          PROFILES
          HASHTAGS
          LANGUAGE
        <p> © 2018 INSTAGRAM </p>
      </nav>
    </footer--> 

app/views/layouts/_likeunlike.html.erb
<div class="col-sm-2" id="likeunlike">
  <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %> 
  <% if pre_like %> 
    <%= button_to  post_like_path(post, pre_like), class: "btn btn-small", method: :delete, remote: true do %> 
      <i class="fa fa-heart fa-2x unlike"> </i> 
    <%end%>
  <%else %> 
    <%= button_to post_likes_path(post), method: :post, class: "btn btn-small", remote: true do %>
      <i class="fa fa-heart-o fa-2x"> </i>
    <%end%>
  <%end%>
</div>  

app/views/layouts/_navbar.html.erb
<nav class="row navbar navbar-expand-lg navbar-light bg-white border-bottom sticky-top">
  <div class="col-sm-2">
  </div>
    
  <div class="col-sm-9">
    <div class="row">  
      
      <div class="col-sm-4">
        <a class="navbar-brand" id="logo" href="<%= root_path %>"> 
          <i class="fa fa-instagram font" aria-hidden="true">
            Imagenate
          </i>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="col-sm-3">
        <%= form_with(url: search_user_path, :method => 'get', class: "form-inline my2 my-lg-0 ", local: true ) do %>
          <%= search_field_tag :search, params[:search], placeholder: "@search", class: "form-control bg-light", remote: false %>  
        <%end%>
      </div> 
      <div class="col-sm-5">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="row navbar-nav ml-auto mr-auto">
            <div class="col-sm-4"> 
              <li class="nav-item active">
                <a><i class="fa fa-compass fa-2x nav-link"></i></a>
              </li> 
            </div>

            <div class="col-sm-4">
              <%= render partial: 'notifications/dropdown', locals: {users: @users } %>
            </div>

            <div class="col-sm-4">
              <li class="nav-item active">
                <a href="<%= profile_path(current_user)%>"><i class="fa fa-user-o fa-2x nav-link"></i> </a>
              </li>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-1">
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
  </div>
</nav>

app/views/layouts/_photos.html.erb
<div class="row">
  <% profile.user.posts.each do |post|%>
    <%if post.images%>
      <%=image_tag(post.images.first.image.url(:small), class: 'media-object img-size m-2')%>
    <%end%>
  <% end %>
</div>

app/views/layouts/_postcard.html.erb
  

<div class="card mr-auto ml-auto pl-auto pr-auto">
  <%= render partial: 'layouts/postcardhead', locals: {post: post} %>
  <%= render partial: 'layouts/carousel', locals: {post: post} %>
  <%= render partial: 'layouts/postcardfooter', locals: {post: post} %>
  <%= render partial: 'layouts/postcarddetails', locals: {post: post} %>
  <%= render partial: 'layouts/commentbox', locals: {post: post} %>
    <%# post_comment = post.comments.find_all { |comment| comment.id != nil} %>
    <%#= render partial: 'comments/comments', collection: post_comment %>
</div>

app/views/layouts/_postcarddetails.html.erb
<div class="post-details card-title">
  <% if !post.user.profile.image.empty? %> 
    <%=image_tag(post.user.profile.image.last.image.url(:thumb), size: '40x40', class: "rounded-circle")%>
  <%end%>
  <div class="pt-1 pl-1" > <strong> <%=post.user&.profile&.username%> </strong>
    <span> <%=post.description%>
  </div>
</div>

app/views/layouts/_postcardfooter.html.erb
<div class="row user-interaction">
  <%= render partial: 'layouts/likeunlike', locals: {post: post} %>  
    <div class="col-sm-2">
        <i class="fa fa-comment-o fa-2x btn btn-small" id= '<%="#{post.id}"%>' onClick= "focusOnCommentField(event)"></i>
    </div>
    <div class="col-sm-2">
      <%= button_to  post_path(post), class: "btn btn-small", method: :get do %> 
        <i class="fa fa-angle-double-right fa-2x"></i> 
      <%end%>
    </div>
    <div class="col-sm-6 like-com comment">
      <strong><%= post.likes.count %></strong> <%=(post.likes.count) == 1 ? 'Like' : 'Likes'%>
      <strong><%= post.comments.count%></strong> <%= (post.comments.count) == 1 ? 'Comment' : 'Comments'%>
      <p> <small class="text-muted"><%=post.updated_at%></small> </p> 
    </div>
  </div>

app/views/layouts/_postcardhead.html.erb
<% if post %>	
	<div class="row">
		<div class="col-sm-2 dp p-0">
			<%if !post.user.profile.image.empty? %> 
		  	<center> <%=image_tag(post.user&.profile&.image&.last&.image&.url(:thumb), size: '60x60')%> </center>
			<%end%>
		</div>
		<div class="col-sm-10 font-weight-bold pt-3">
			<span> <%=link_to post.user&.profile&.username, profile_path(post.user), class: 'text-dark'%> </span>
		</div>
	</div>
<%end%>

app/views/layouts/_profiledetails.html.erb
<div class="card mb-5 border-0 ">
  <div class="row no-gutters">
    <div class="col-md-4">
        <%if profile.image.length > 0 %>
          <%= image_tag(profile.image.last.image.url(:small), class: 'media-object img-size rounded-circle', size: '150x150') %>
        <%end%>
    </div>
    <div class="col-md-8">
      <div class="card-body row m-0 p-0">
        <div class="col-sm-6 m-0 p-0">
          <h4 class="card-title m-0 p-0"><%=profile.username%></h4>
        </div>
        <div class="col-sm-6">
          <%= button_to 'Edit Profile', edit_profile_path(current_user), class: "btn btn-default border", method: :get  %>
        </div>
      </div>
      <p class="text-muted font-weight-bold"><%=profile.name%></p>
      <p class="card-text font-weight-lighter"><%=profile.bio%></p>
    </div>
  </div>
</div>
  <%if !profile.user.posts.empty? %> 
    <div class="row">
      <p class="font-weight-bold mx-auto"> <i class="fa fa-th"></i> POSTS</p>
    </div>    
    <div class="row">
      <%= render partial:'layouts/photos', locals: {profile: profile } %>
    </div>
  <%else%>
      <strong>You don't have any post! </strong><%= link_to 'Click to Create',new_post_path, method: :get, class: "font-weight-bold btn btn-outline-secondary" %>
  <%end%>

app/views/layouts/_suggested.html.erb
  <h6 class="font-weight-bold m-2 ">Suggested Peoples</h6> 
  <div class="suggested overflow-auto m-0 p-0 ">
    <%@users.each do |user|%>  
      <% if user.id != current_user.id %>
        <div class="row m-0 p-0">
          <div class="col-md-6 p-0 m-0">
            <strong>  <%= link_to user.profile.username, profile_path(user), class:'text-secondary m-0 p-0' %> </strong>
          </div>  
          <div class="col-md-6 p-0 m-0">
            <%= render partial: 'layouts/followbutton', locals: {user: user} %>
          </div>
        </div>
      <% end %> 
      <br>  
    <% end %>
  </div>
  </div>

app/views/layouts/_userdetail.html.erb
	<div class="row">
		<div class="col-sm-2 dp p-0">
			<%if current_user.profile.image.length > 0 %> 
		  	<center> <%=image_tag(current_user.profile&.image&.last&.image&.url(:thumb), size: '60x60')%> </center>
			<%end%>
		</div>
		<div class="col-sm-10 font-weight-bold pt-3">
		  <span> <%=link_to current_user&.profile&.username, profile_path(current_user), class: 'text-dark'%> </span>
      <p> <small class="text-muted font-weight-bold"><%=current_user.profile.name%></small></p>
    </div>
	</div>

app/views/layouts/_usersection.html.erb
<%= render partial: 'layouts/userdetail'%>
<div class="card w-100 p-20 mt-5 fixed">
  <div class="row card-body ">
    <h5 class="card-title font-weight-light "> <%=current_user.profile.name%> </h5>
  </div>

  <div class="row card-body">
    <div class="col-sm-6">
      <%= button_to 'Create Post',new_post_path, method: :get, class: "btn btn-outline-secondary" %>
    </div>
    <div class="col-sm-6">
      <%= button_to 'Update Profile',edit_profile_path(current_user), method: :get, class: "btn btn-outline-secondary" %>
    </div>
  </div>
  <%= render partial: 'layouts/suggested'%>
  <%= render partial: 'layouts/footerdetails'%>
</div>

app/views/notifications/_dropdown.html.erb
<li class="nav-item dropdown">
  <a class="nav-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="<%= request_path(current_user)%>"><i class="fa fa-heart-o fa-2x"></i></a>
  <div class="dropdown-menu dropdown-menu-right overflow-auto p-3" aria-labelledby="navbarDropdown">
    <% if current_user.requesters.empty? %>
      <h6 class="text-muted">There are no Follow Request for you ! </h6>
  <% else %>
    <%current_user.requesters.each do |user|%>  
      <%= render partial: 'notifications/followrequest', locals: {user: user} %>
    <%end%>
  <%end%>
  </div>
</li>

app/views/notifications/_followrequest.html.erb
  <%if params[:status] != "declined"%>
    <div class="row m-2 p-0 mb-2", id="follow_request<%=user.id%>">
      <div class="col-sm-2 p-0 m-0">
            <%= image_tag(user.profile.image.last.image.url(:small), alt: "Image", size:'50x50', class:'rounded-circle')%>
      </div>
      <div class="col-sm-5 p-0 m-0">
            <%= link_to "#{user.profile.username}", profile_path(user), class: 'text-dark font-weight-bold' %>
      </div>
      <div class="col-sm-5 p-0 m-0">
        <div class="row">
          <div class="col-sm-6">
            <%= button_to "Decline", request_path(user_id: user.id, status: :declined), class: "btn btn-outline-danger", :method => :post, remote: :true %>
          </div>
          <div class="col-sm-6">
            <%= button_to "Accept", relationships_path(user_id: user.id), class: "btn btn-outline-success", :method => :post %>
          </div>
        </div>
      </div>
    </div>
  <%else%>
    <h6 class="text-muted">There are no Follow Request for you ! </h6>
  <%end%>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div>
    <div>
      <h5>Errors while saving </h5>
    </div>
  
    <ul>
      <% object.errors.full_message.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
<%end%> 

app/views/shared/_form.html.erb
<div class="row pt-4">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4">
    <%= form_for @post, url: {action: "create"}  do |f| %>
      <%= render 'shared/errors', object: @post %>
        <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: 'form-control', multiple: true, :multiple => true%>
        </div>

      <%= f.submit 'Submit', class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/shared/_image.html.erb
<div class="reflection">
  <%= image_tag("login.jpg", alt: "login photo", id: "image-1") %>
</div>

app/views/shared/_logo.html.erb
  <div class="m-3 ml-3  ">  
    <span><a href="<%= root_path %>", class="text-secondary"></span>
      <i class="fa fa-instagram fa-lg font" aria-hidden="true">
      Imagenate
      </i> 
    </a>
  </div>